<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.project60.banking/xml/schema/CRM/Banking/BankTransaction.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:6d7188a6d2ad3f8a467a71bf9ed5b5bc)
 */
use CRM_Banking_ExtensionUtil as E;

/**
 * Database access object for the BankTransaction entity.
 */
class CRM_Banking_DAO_BankTransaction extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_bank_tx';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * The unique reference for this transaction
   *
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $bank_reference;

  /**
   * Value date for this bank transaction
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $value_date;

  /**
   * Booking date for this bank transaction
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $booking_date;

  /**
   * Transaction amount (positive or negative)
   *
   * @var float|string
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $amount;

  /**
   * Currency for the amount of the transaction
   *
   * @var string|null
   *   (SQL type: varchar(3))
   *   Note that values will be retrieved from the database as a string.
   */
  public $currency;

  /**
   * Link to an option list
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $type_id;

  /**
   * Link to an option list
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $status_id;

  /**
   * The complete information received for this transaction
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $data_raw;

  /**
   * A JSON-formatted array containing decoded fields
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $data_parsed;

  /**
   * FK to bank_account of target account
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $ba_id;

  /**
   * FK to bank_account of party account
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $party_ba_id;

  /**
   * FK to parent bank_tx_batch
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $tx_batch_id;

  /**
   * Numbering local to the tx_batch_id
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sequence;

  /**
   * A JSON-formatted array containing suggestions
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $suggestions;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_bank_tx';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Bank Transactions') : E::ts('Bank Transaction');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.id',
          'export' => TRUE,
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'bank_reference' => [
          'name' => 'bank_reference',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Unique Statement Reference'),
          'description' => E::ts('The unique reference for this transaction'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.bank_reference',
          'export' => TRUE,
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'value_date' => [
          'name' => 'value_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Value date'),
          'description' => E::ts('Value date for this bank transaction'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.value_date',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'booking_date' => [
          'name' => 'booking_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Booking date'),
          'description' => E::ts('Booking date for this bank transaction'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.booking_date',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
          ],
          'add' => NULL,
        ],
        'amount' => [
          'name' => 'amount',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Transaction amount'),
          'description' => E::ts('Transaction amount (positive or negative)'),
          'required' => TRUE,
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.amount',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'currency' => [
          'name' => 'currency',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Currency'),
          'description' => E::ts('Currency for the amount of the transaction'),
          'maxlength' => 3,
          'size' => CRM_Utils_Type::FOUR,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.currency',
          'dataPattern' => '/^[A-Z]{3}$/i',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'type_id' => [
          'name' => 'type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Bank Transaction Type'),
          'description' => E::ts('Link to an option list'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.type_id',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'status_id' => [
          'name' => 'status_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Bank Transaction Status'),
          'description' => E::ts('Link to an option list'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.status_id',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'optionGroupName' => 'civicrm_banking.bank_tx_status',
            'keyColumn' => 'id',
            'optionEditPath' => 'civicrm/admin/options/civicrm_banking.bank_tx_status',
          ],
          'add' => NULL,
        ],
        'data_raw' => [
          'name' => 'data_raw',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Data Raw'),
          'description' => E::ts('The complete information received for this transaction'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.data_raw',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'data_parsed' => [
          'name' => 'data_parsed',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Data Parsed'),
          'description' => E::ts('A JSON-formatted array containing decoded fields'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.data_parsed',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
        'ba_id' => [
          'name' => 'ba_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Bank Account ID'),
          'description' => E::ts('FK to bank_account of target account'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.ba_id',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'FKClassName' => 'CRM_Banking_DAO_BankAccount',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'party_ba_id' => [
          'name' => 'party_ba_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Party Bank Account ID'),
          'description' => E::ts('FK to bank_account of party account'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.party_ba_id',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'FKClassName' => 'CRM_Banking_DAO_BankAccount',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'tx_batch_id' => [
          'name' => 'tx_batch_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Bank Transaction Batch ID'),
          'description' => E::ts('FK to parent bank_tx_batch'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.tx_batch_id',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'FKClassName' => 'CRM_Banking_DAO_BankTransactionBatch',
          'html' => [
            'type' => 'EntityRef',
          ],
          'add' => NULL,
        ],
        'sequence' => [
          'name' => 'sequence',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Sequence in statement'),
          'description' => E::ts('Numbering local to the tx_batch_id'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.sequence',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'add' => NULL,
        ],
        'suggestions' => [
          'name' => 'suggestions',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Suggestions'),
          'description' => E::ts('A JSON-formatted array containing suggestions'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_tx.suggestions',
          'table_name' => 'civicrm_bank_tx',
          'entity' => 'BankTransaction',
          'bao' => 'CRM_Banking_DAO_BankTransaction',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'bank_tx', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'bank_tx', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'bank_reference' => [
        'name' => 'bank_reference',
        'field' => [
          0 => 'bank_reference',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_bank_tx::1::bank_reference',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
