<?php
/*-------------------------------------------------------+
| Project 60 - CiviBanking                               |
| Copyright (C) 2013-2021 SYSTOPIA                       |
| Author: B. Endres (endres -at- systopia.de)            |
| http://www.systopia.de/                                |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL v3 license. You can redistribute it and/or  |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*/

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.project60.banking/xml/schema/CRM/Banking/BankAccount.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:16eea7015e1b848b9acc6973fde4f199)
 */
use CRM_Banking_ExtensionUtil as E;

/**
 * Database access object for the BankAccount entity.
 */
class CRM_Banking_DAO_BankAccount extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '4.3';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_bank_account';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * ID
   *
   * @var int
   */
  public $id;

  /**
   * Purpose or use of the bank account
   *
   * @var string
   */
  public $description;

  /**
   * @var datetime
   */
  public $created_date;

  /**
   * @var datetime
   */
  public $modified_date;

  /**
   * The complete information received for this bank account
   *
   * @var text
   */
  public $data_raw;

  /**
   * A JSON-formatted array containing decoded fields
   *
   * @var text
   */
  public $data_parsed;

  /**
   * FK to contact owning this account
   *
   * @var int
   */
  public $contact_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_bank_account';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Bank Accounts') : E::ts('Bank Account');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('ID'),
          'required' => TRUE,
          'where' => 'civicrm_bank_account.id',
          'export' => TRUE,
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Description'),
          'description' => E::ts('Purpose or use of the bank account'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_bank_account.description',
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Date created'),
          'required' => TRUE,
          'where' => 'civicrm_bank_account.created_date',
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Date modified'),
          'required' => TRUE,
          'where' => 'civicrm_bank_account.modified_date',
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'data_raw' => [
          'name' => 'data_raw',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Data Raw'),
          'description' => E::ts('The complete information received for this bank account'),
          'where' => 'civicrm_bank_account.data_raw',
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'data_parsed' => [
          'name' => 'data_parsed',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Data Parsed'),
          'description' => E::ts('A JSON-formatted array containing decoded fields'),
          'where' => 'civicrm_bank_account.data_parsed',
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to contact owning this account'),
          'where' => 'civicrm_bank_account.contact_id',
          'table_name' => 'civicrm_bank_account',
          'entity' => 'BankAccount',
          'bao' => 'CRM_Banking_DAO_BankAccount',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => '4.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'bank_account', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'bank_account', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
