<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from org.project60.banking/xml/schema/CRM/Banking/PluginInstance.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:4bfa6e282cc9dfe9aaa36bb0cb3430d8)
 */
use CRM_Banking_ExtensionUtil as E;

/**
 * Database access object for the PluginInstance entity.
 */
class CRM_Banking_DAO_PluginInstance extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '4.3';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_bank_plugin_instance';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Link to an option list of plugin types
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $plugin_type_id;

  /**
   * Link to an option list of plugin class names
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $plugin_class_id;

  /**
   * Name of the plugin
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Short description of what the plugin does
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * If this plugin is enabled
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $enabled;

  /**
   * Relative weight of this plugin
   *
   * @var float|string
   *   (SQL type: double)
   *   Note that values will be retrieved from the database as a string.
   */
  public $weight;

  /**
   * Configuration JSON
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $config;

  /**
   * State JSON
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $state;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_bank_plugin_instance';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Plugin Instances') : E::ts('Plugin Instance');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => TRUE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.id',
          'export' => TRUE,
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => '4.3',
        ],
        'plugin_type_id' => [
          'name' => 'plugin_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Plugin type'),
          'description' => E::ts('Link to an option list of plugin types'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.plugin_type_id',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'civicrm_banking.plugin_types',
            'keyColumn' => 'id',
            'optionEditPath' => 'civicrm/admin/options/civicrm_banking.plugin_types',
          ],
          'add' => '4.3',
        ],
        'plugin_class_id' => [
          'name' => 'plugin_class_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Plugin class name'),
          'description' => E::ts('Link to an option list of plugin class names'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.plugin_class_id',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'civicrm_banking.plugin_classes',
            'keyColumn' => 'id',
            'optionEditPath' => 'civicrm/admin/options/civicrm_banking.plugin_classes',
          ],
          'add' => '4.3',
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Name of the plugin'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.name',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'description' => E::ts('Short description of what the plugin does'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.description',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'enabled' => [
          'name' => 'enabled',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Enabled'),
          'description' => E::ts('If this plugin is enabled'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.enabled',
          'default' => '1',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'weight' => [
          'name' => 'weight',
          'type' => CRM_Utils_Type::T_FLOAT,
          'title' => E::ts('Weight'),
          'description' => E::ts('Relative weight of this plugin'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.weight',
          'default' => '100.0',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'config' => [
          'name' => 'config',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Config'),
          'description' => E::ts('Configuration JSON'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.config',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'add' => '4.3',
        ],
        'state' => [
          'name' => 'state',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('State'),
          'description' => E::ts('State JSON'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_bank_plugin_instance.state',
          'table_name' => 'civicrm_bank_plugin_instance',
          'entity' => 'PluginInstance',
          'bao' => 'CRM_Banking_DAO_PluginInstance',
          'localizable' => 0,
          'add' => '4.3',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'bank_plugin_instance', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'bank_plugin_instance', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
