<?php
/*
    org.project60.banking extension for CiviCRM

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

/**
 * The Ignore matcher can be configured with regular expressions to automatically ignore
 *   certain payments
 */
class CRM_Banking_PluginImpl_Matcher_Ignore extends CRM_Banking_PluginModel_Matcher {

  /**
   * class constructor
   */
  function __construct($config_name) {
    parent::__construct($config_name);
  }

  public function match(CRM_Banking_BAO_BankTransaction $btx, CRM_Banking_Matcher_Context $context) {

    // this section will be refactored to use different conditions, but for now, this is hardcoded
    $suggestion = new CRM_Banking_Matcher_Suggestion($this, $btx);

    $config = $this->_plugin_config;

    if (isset($config->ignore)) {
      // iterate through the ignore list
      foreach ($config->ignore as $ignore_record) {
        if ($this->matches_pattern($ignore_record, $btx, $context)) {
          if (isset($ignore_record->precision)) {
            $suggestion->addEvidence($ignore_record->precision, $ignore_record->message);
          } else {
            $suggestion->addEvidence(1, $ignore_record->message);
          }
        }
      }
    }

    if ($suggestion->getProbability() > 0) {
      $btx->addSuggestion($suggestion);
    }

    // that's it...
    return empty($this->_suggestions) ? null : $this->_suggestions;
  }


  /**
   * Handle the different actions, should probably be handles at base class level ...
   * 
   * @param type $match
   * @param type $btx
   */
  public function execute($suggestion, $btx) {
    // this is the IGNORE action. Simply set the status to ignored
    $newStatus = banking_helper_optionvalueid_by_groupname_and_name('civicrm_banking.bank_tx_status', 'Ignored');
    $btx->setStatus($newStatus);
  }


  /**
   * check if this ignore pattern applies to this btx
   */
  private function matches_pattern($ignore_record, CRM_Banking_BAO_BankTransaction $btx, CRM_Banking_Matcher_Context $context) {
    // collect all the fields
    $fields = array();
    if (isset($ignore_record->field)) {
      array_push($fields, $ignore_record->field);
    }

    if (isset($ignore_record->fields)) {
      $fields = array_merge($fields, $ignore_record->fields);
    }

    // extract the values
    $values = array();
    foreach ($fields as $field) {
      if (isset($btx->$field)) {
        array_push($values, $btx->$field);
      } else {
        $data = $btx->getDataParsed();
        if (isset($data[$field])) {
          array_push($values, $data[$field]);
        }
      }
    }

    if (isset($ignore_record->regex)) {
      foreach ($values as $value) {
        if (preg_match($ignore_record->regex, $value)) {
          return true;
        }
      }
    }
    
    return false;
  }
  

  /** 
   * Generate html code to visualize the executed match.
   * 
   * @val $match    match data as previously generated by this plugin instance
   * @val $btx      the bank transaction the match refers to
   * @return html code snippet
   */  
  function visualize_execution_info( CRM_Banking_Matcher_Suggestion $match, $btx) {
    $html = "<p>".ts("Because :")."<ul>";
    $evidence = $match->getEvidence();
    foreach ($evidence as $ev) {
      $html .= '<li>' . $ev . '</li>';
    }
    $html .= '</ul></p>';
    return $html;
  }

}

