<?php
/*
    org.project60.banking extension for CiviCRM

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/



/**
 * This is a dummy matcher for testing purposes only
 */
class CRM_Banking_PluginImpl_Matcher_Yes extends CRM_Banking_PluginModel_Matcher {

  /**
   * class constructor
   */
  function __construct($config_name) {
    parent::__construct($config_name);
  }

  public function match(CRM_Banking_BAO_BankTransaction $btx, CRM_Banking_Matcher_Context $context) {
    $suggestion = new CRM_Banking_Matcher_Suggestion($this, $btx);
    $suggestion->addEvidence( 1.0, "Yes we can" );
    return array($suggestion);
  }

  /**
   * Handle the different actions, should probably be handles at base class level ...
   * 
   * @param type $match
   * @param type $btx
   */
  public function execute($match, $btx) {
    
  }

  public function visualize_match(CRM_Banking_Matcher_Suggestion $match, $btx) {
    return '<div style="background-color:gray;text-align:center">
            <font size="+1">
            <font color="#ccff66">Y</font>
            <font color="#84ed42">E</font>
            <font color="#54e12a">S</font>
            <font color="#3cdb1e">!</font>
            <font color="#24d512">!</font>
            <font color="#0ccf06">!</font>
            </font>
            </div>';
  }

  /** 
   * Generate html code to visualize the executed match.
   * 
   * @val $match    match data as previously generated by this plugin instance
   * @val $btx      the bank transaction the match refers to
   * @return html code snippet
   */  
  function visualize_execution_info( CRM_Banking_Matcher_Suggestion $match, $btx) {
    return "<p>Why? Because.</p>";
  }

}


