<h3>Status: {$status_message}</h3>

{* This page is generated by CRM/Banking/Page/Payments.php *}

{if $show=='payments'}
  <a class="button" href="{$url_show_statements}">
    <span><div class="icon details-icon"></div>Show Statements</span>
  </a>
{else}
  <a class="button" href="{$url_show_payments}">
    <span><div class="icon details-icon"></div>Show Payments</span>
  </a>
{/if}

<a class="button" href="{$url_show_payments_new}">
  <span><div class="icon inform-icon"></div>New</span>
</a>
<a class="button" href="{$url_show_payments_analysed}">
  <span><div class="icon inform-icon"></div>Analysed</span>
</a>
<a class="button" href="{$url_show_payments_completed}">
  <span><div class="icon inform-icon"></div>Completed</span>
</a>
<a class="button" href="#">
  <span><div class="icon edit-icon"></div>Custom Filter</span>
</a>

<table id="contact-activity-selector-dashlet">
{if $show=='payments'}
<thead>
	<tr>
		<th colspan="1" rowspan="1" class="ui-state-default">
			<div class="DataTables_sort_wrapper"><span class="DataTables_sort_icon"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_date ui-state-default">
			<div class="DataTables_sort_wrapper">Date<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_amount ui-state-default">
			<div class="DataTables_sort_wrapper">Amount<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_target_owner ui-state-default">
			<div class="DataTables_sort_wrapper">Account Owner<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_source_account nosort ui-state-default">
			<div class="DataTables_sort_wrapper">Source Account<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="ccrm-banking-payment_target_account nosort ui-state-default">
			<div class="DataTables_sort_wrapper">Target Account<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="ccrm-banking-payment_state ui-state-default">
			<div class="DataTables_sort_wrapper">State<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
    <th colspan="1" rowspan="1" class="ui-state-default">
      <div class="DataTables_sort_wrapper"><span></span></div>
    </th>
		<th colspan="1" rowspan="1" class="hiddenElement ui-state-default">
			<div class="DataTables_sort_wrapper">&nbsp;<span class="DataTables_sort_icon"></span></div>
		</th>
	</tr>
</thead>
<tbody>
  {foreach from=$rows item=field key=fieldName}
  <tr class="odd status-overdue">
    <td><input id="check_{$field.id}" type="checkbox" name="payment_selected"></td>
    <td class="crm-contact-activity-activity_date">{$field.date}</td>
    <td class="crm-contact-activity-activity_type">{$field.amount}</td>
    <td class="crm-contact-activity-source_contact">{$field.account_owner}</td>
    <td class="crm-contact-activity-source_contact">{$field.source}</td>
    <td class="crm-contact-activity-source_contact">{$field.target}</td>
    <td class="crm-contact-activity_subject">{$field.state}</td>
    <td class="crm-contact-activity_link"><a href="{$field.url_link}">view</a></td>
    <td class="hiddenElement">status-overdue</td>
  </tr>
  {/foreach}
</tbody>

{else} {* STATEMENTS *}
<thead>
  <tr>
    <th colspan="1" rowspan="1" class="ui-state-default">
      <div class="DataTables_sort_wrapper"><span class="DataTables_sort_icon"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_date ui-state-default">
      <div class="DataTables_sort_wrapper">Statement<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_date ui-state-default">
      <div class="DataTables_sort_wrapper">Date<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_amount ui-state-default">
      <div class="DataTables_sort_wrapper">Payment count<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="ccrm-banking-payment_target_account nosort ui-state-default">
      <div class="DataTables_sort_wrapper">Target Account<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_source_account nosort ui-state-default">
      <div class="DataTables_sort_wrapper">Analysed<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_source_account nosort ui-state-default">
      <div class="DataTables_sort_wrapper">Completed<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="hiddenElement ui-state-default">
      <div class="DataTables_sort_wrapper">&nbsp;<span class="DataTables_sort_icon"></span></div>
    </th>
  </tr>
</thead>
<tbody>
  {foreach from=$rows item=field key=fieldName}
  <tr class="odd status-overdue">
    <td><input id="check_{$field.id}" type="checkbox" name="payment_selected"></td>
    <td class="crm-contact-activity-activity_date">{$field.reference}</td>
    <td class="crm-contact-activity-activity_type">{$field.date}</td>
    <td class="crm-contact-activity-source_contact">{$field.count}</td>
    <td class="crm-contact-activity-source_contact">{$field.target}</td>
    <td class="crm-contact-activity-source_contact">{$field.analysed}</td>
    <td class="crm-contact-activity-source_contact">{$field.completed}</td>
    <td class="crm-contact-activity_subject">{$field.state}</td>
    <td class="hiddenElement">status-overdue</td>
  </tr>
  {/foreach}
</tbody>
{/if}
</table>


<input onClick="selectAll(true)" class="form-submit" type="submit" value="Select all" width="200"></input>
<input onClick="selectAll(false)" class="form-submit" type="submit" value="Select none" width="200"></input>	
<p>With selected items perform:<br/>
<a class="button" onClick="callWithSelected('{$url_review_selected_payments}')" ><span>Review</span></a>
<a class="button" onClick="callWithSelected('{$url_process_selected_payments}')"><span>Process</span></a>
<a class="button" onClick="callWithSelected('{$url_export_selected_payments}')"><span>Export</span></a>
<a class="button" onClick="callWithSelected('{$url_delete_selected_payments}')"><span>Delete</span></a>
</p>



<!-- Required JavaScript functions -->
{literal}
<script language="JavaScript">

function selectAll(value) {
  checkboxes = document.getElementsByName('payment_selected');
  for(var i=0, n=checkboxes.length; i<n; i++) {
    checkboxes[i].checked = value;
  }
}

function getSelected() {
  checkboxes = document.getElementsByName('payment_selected');
  var selected = "";
  for(var i=0, n=checkboxes.length; i<n; i++) {
    if (checkboxes[i].checked) {
      id = checkboxes[i].id;
      if (selected.length) selected += ",";
      selected += checkboxes[i].id.substring(6)
      //selected.push(checkboxes[i].id.substring(6));
    }
  }
  console.log(selected);
  return selected;
}

function callWithSelected(url) {
  location.href = url.replace("__selected__",getSelected());
}

</script>
{/literal} 

