
<h3>Status: {$status_message}</h3>

{* This page is generated by CRM/Banking/Page/Payments.php *}

<!-- potentially: ul class="crm-extensions-tabs-list ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all" role="tablist">
  <li class="crm-tab-button ui-state-default ui-corner-top ui-corner-bottom" id="tab_summary" role="tab" tabindex="-1" aria-controls="extensions-main" aria-labelledby="ui-id-1" aria-selected="false"><a title="Extensions" href="#extensions-main" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-1"><span> </span> Extensions              <em>&nbsp;</em></a></li>
  <li class="crm-tab-button ui-state-default ui-corner-top ui-corner-bottom ui-tabs-active ui-state-active" id="tab_addnew" role="tab" tabindex="0" aria-controls="extensions-addnew" aria-labelledby="ui-id-2" aria-selected="true">
              <a title="Add New" href="#extensions-addnew" class="ui-tabs-anchor" role="presentation" tabindex="-1" id="ui-id-2">
              <span> </span> Add New              <em>&nbsp;</em>
              </a>
            </li>
</ul-->

{if $show=='payments'}
  <a class="button" href="{$url_show_statements}">
    <span><div class="icon details-icon"></div>Show Statements</span>
  </a>
{else}
  <a class="button" href="{$url_show_payments}">
    <span><div class="icon details-icon"></div>Show Payments</span>
  </a>
{/if}

<a class="button" href="{$url_show_payments_new}">
  <span><div class="icon inform-icon"></div>New</span>
</a>
<a class="button" href="{$url_show_payments_analysed}">
  <span><div class="icon inform-icon"></div>Analysed</span>
</a>
<a class="button" href="{$url_show_payments_completed}">
  <span><div class="icon inform-icon"></div>Completed</span>
</a>
<a class="button" href="#">
  <span><div class="icon edit-icon"></div>Custom Filter</span>
</a>

<table id="contact-activity-selector-dashlet">
{if $show=='payments'}
<thead>
	<tr>
		<th colspan="1" rowspan="1" class="ui-state-default">
			<div class="DataTables_sort_wrapper"><span class="DataTables_sort_icon"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_date ui-state-default">
			<div class="DataTables_sort_wrapper">Date<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_amount ui-state-default">
			<div class="DataTables_sort_wrapper">Amount<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_target_owner ui-state-default">
			<div class="DataTables_sort_wrapper">Account Owner<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="crm-banking-payment_source_account nosort ui-state-default">
			<div class="DataTables_sort_wrapper">Source Account<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="ccrm-banking-payment_target_account nosort ui-state-default">
			<div class="DataTables_sort_wrapper">Target Account<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
		<th colspan="1" rowspan="1" class="ccrm-banking-payment_state ui-state-default">
			<div class="DataTables_sort_wrapper">State<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
		</th>
    <th colspan="1" rowspan="1" class="ui-state-default">
      <div class="DataTables_sort_wrapper"><span></span></div>
    </th>
		<th colspan="1" rowspan="1" class="hiddenElement ui-state-default">
			<div class="DataTables_sort_wrapper">&nbsp;<span class="DataTables_sort_icon"></span></div>
		</th>
	</tr>
</thead>
<tbody>
  {foreach from=$rows item=field key=fieldName}
  <tr class="odd status-overdue">
    <td><input id="check_{counter}" type="checkbox" name="paymentList[{counter}]"></td>
    <td class="crm-contact-activity-activity_date">{$field.date}</td>
    <td class="crm-contact-activity-activity_type">{$field.amount}</td>
    <td class="crm-contact-activity-source_contact">{$field.account_owner}</td>
    <td class="crm-contact-activity-source_contact">{$field.source}</td>
    <td class="crm-contact-activity-source_contact">{$field.target}</td>
    <td class="crm-contact-activity_subject">{$field.state}</td>
    <td class="crm-contact-activity_link"><a href="{$field.url_link}">view</a></td>
    <td class="hiddenElement">status-overdue</td>
  </tr>
  {/foreach}
</tbody>
{else}
<thead>
  <tr>
    <th colspan="1" rowspan="1" class="ui-state-default">
      <div class="DataTables_sort_wrapper"><span class="DataTables_sort_icon"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_date ui-state-default">
      <div class="DataTables_sort_wrapper">Statement<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_date ui-state-default">
      <div class="DataTables_sort_wrapper">Date<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_amount ui-state-default">
      <div class="DataTables_sort_wrapper">Payment count<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="ccrm-banking-payment_target_account nosort ui-state-default">
      <div class="DataTables_sort_wrapper">Target Account<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_source_account nosort ui-state-default">
      <div class="DataTables_sort_wrapper">Analysed<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="crm-banking-payment_source_account nosort ui-state-default">
      <div class="DataTables_sort_wrapper">Completed<span class="DataTables_sort_icon css_right ui-icon ui-icon-carat-2-n-s"></span></div>
    </th>
    <th colspan="1" rowspan="1" class="hiddenElement ui-state-default">
      <div class="DataTables_sort_wrapper">&nbsp;<span class="DataTables_sort_icon"></span></div>
    </th>
  </tr>
</thead>
<tbody>
  {foreach from=$rows item=field key=fieldName}
  <tr class="odd status-overdue">
    <td><input id="check_{counter}" type="checkbox" name="paymentList[{counter}]"></td>
    <td class="crm-contact-activity-activity_date">{$field.id}</td>
    <td class="crm-contact-activity-activity_type">{$field.date}</td>
    <td class="crm-contact-activity-source_contact">{$field.count}</td>
    <td class="crm-contact-activity-source_contact">{$field.target}</td>
    <td class="crm-contact-activity-source_contact">{$field.analysed}</td>
    <td class="crm-contact-activity-source_contact">{$field.completed}</td>
    <td class="crm-contact-activity_subject">{$field.state}</td>
    <td class="hiddenElement">status-overdue</td>
  </tr>
  {/foreach}
</tbody>
{/if}
</table>
<input id="" class="form-submit" type="submit" value="Select all" width="200" name=""></input>
<input id="" class="form-submit" type="submit" value="Select none" width="200" name=""></input>	
<p>With selected items perform:<br/>
<a class="button" href="{$url_show_all}"><span>Review</span></a>
<a class="button" href="#"><span>Process</span></a>
<a class="button" href="#"><span>Export</span></a>
<a class="button" href="#"><span>Delete</span></a>
</p>