{*-------------------------------------------------------+
| Project 60 - CiviBanking                               |
| Copyright (C) 2013-2014 SYSTOPIA                       |
| Author: B. Endres (endres -at- systopia.de)            |
| http://www.systopia.de/                                |
+--------------------------------------------------------+
| This program is released as free software under the    |
| Affero GPL v3 license. You can redistribute it and/or  |
| modify it under the terms of this license which you    |
| can read by viewing the included agpl.txt or online    |
| at www.gnu.org/licenses/agpl.html. Removal of this     |
| copyright header is strictly prohibited without        |
| written permission from the original author(s).        |
+--------------------------------------------------------*}

{literal}
  <style>
    #btx-details .btxheader.collapsible-closed {
      background: url("{$base_url}/sites/all/modules/civicrm/i/TreeMinus.gif")  4px 4px no-repeat;
      background-color: #CCC;
      color: #000;
      font-weight: bold;
      padding-left: 20px;
    }
    #btx-details .btxheader {
      background: url("{$base_url}/sites/all/modules/civicrm/i/TreePlus.gif") 4px 4px no-repeat;
      background-color: #CCC;
      color: #000;
      font-weight: bold;
      padding-left: 20px;
    }
    #btx {
      background-color: #F4F4ED;
    }
    #btx div {
    }
    #btx div.content {
      padding: 4px 8px;;
      margin: 0;
      border: none;
      background-color: #f7f7f7;
    }
    #btx h4 {
      width: auto;
      background-color: #CCC;
      margin: 0px;
      padding: 2px 8px;
      color: #000;
    }
    #btx table td {
      padding: 0;
    }
    #btx table td div {
      padding: 2px 8px;
    }
    #btx-amt {
      float: left;
      width: 25%;
      margin: 0;
    }
    #btx-info {
      float: left;
      width: 25%;
      margin: 0;
    }
    #btx-debtor {
      float: left;
      width: 50%;
      margin: 0;
    }
    #btx-purpose {
      float: left;
      width: 100%;
      margin: 0;
    }
    #btx-details {
      float: left;
      width: 100%;
      margin: 0;
    }
    td.btx-detail-entry {
      white-space: pre-wrap;
      font-family: Courier;
    }
    .btxvalue {
      background-color: #F4F4ED;
      border-bottom: 1px solid white;
    }
    .btxc {
      text-align: center;
    }
    .btxl {
      text-align: left;
    }
    .btxamt {
      text-align: right;
      font-size: 36px;
      font-weight: bold;
      padding: 4px 8px;
      line-height: 1.2em;
    }
    .btxamtlarge {
      font-size: 32px !important;
    }
    .btxamtneg {
      color: red;
    }
    .btxlabel {
      background-color: #FAFAFA;
      float: left;
      width: 46px;
      font-size: 9px;
      color: #999;
      margin-right: 4px;
    }
    .btxcurr {
      float: right;
      font-size: 10px;
      font-weight: normal;
      line-height: 10px;
      vertical-align: top;
    }
    .btxheader {
      background-color: #CCC;
      color: #000;
      font-weight: bold;
      padding-left: 20px;
    }
    table.suggestions table {
      border: 0px solid red !important;
    }
    table.suggestions tr td.layout {
      padding: 0px !important;
    }
    table.suggestions table tr.suggestion {
      background-color: #fafafa;
    }
    table.suggestions table tr.suggestion:hover {
      background-color: #eee;
    }
    table.suggestions table tr.suggestion-selected {
      background-color: #e6e6bb;
      border: 2px solid gray;
    }
    table.suggestions table tr.suggestion-selected:hover {
      background-color: #dedeb6;
      border: 2px solid gray;
    }
    td.prob {
      font-size: 18px;
      font-weight: bold;
      padding:  8px 4px;
      text-align: center;
    }
    td.suggest {
      font-family: Georgia,"Times New Roman",Times,serif;
      font-size: 14px;
      color: #666;
      padding:  8px;
    }
    td.suggest h4 {
      font-family: Arial,sans-serif;
      font-size: 18px;
      font-weight: bold;
      margin: 0 0 4px 0;
      padding-left: 4px;
      color: #000;
    }
    td.suggest ul {
      margin: 0px;
      padding: 4px;
    }
    td.suggest ul li{
      margin: 0 0 0 15px;
    }
    table.explorer td.xk {
      background-color: #FAFAFA;
      font-size: 10px;
      color: #999;
      width: 25%;
    }
    table.explorer td {
      background-color: #F4F4ED;
      border-bottom: 1px solid white;
      padding: 1px 4px !important;
    }
  </style>
{/literal}

{* This page is generated by CRM/Banking/Page/Review.php *}

  <div id="btx">
    <table id="btx-amt">
      <tr>
        <td>
          <div class="btxheader">
            {ts domain='org.project60.banking'}BASIC INFO{/ts}
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="btxvalue btxamt{if $payment->amount lt 0} btxamtneg{/if}{if $payment->amount gte 10000} btxamtlarge{/if}{if $payment->amount lte -10000} btxamtlarge{/if}">
            <div class="btxcurr">{$payment->currency}</div>
            {$payment->amount}
          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Booking{/ts}</div>
          <div class="btxvalue btxc">
            {$payment->booking_date|truncate:10:''}
          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Value{/ts}</div>
          <div class="btxvalue btxc">
            {$payment->value_date|truncate:10:''}
          </div>
        </td>
      </tr>
    </table>
    <table id="btx-info">
      <tr>
        <td>
          <div class="btxheader">
            {ts domain='org.project60.banking'}TRANSACTION INFO{/ts}
          </div>
        </td>
      </tr>
      <tr>
        <td>
          <div class="btxvalue">
            {$my_bao->description}
          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Stmt. #{/ts}</div>
          <div class="btxvalue btxc">
            {$payment->tx_batch_id}&nbsp;
          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Trans. #{/ts}</div>
          <div class="btxvalue btxc">
            {$payment->id}&nbsp;
          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Status{/ts}</div>
          <div class="btxvalue btxc">
            {$btxstatus.label}
          </div>
        </td>
      </tr>
    </table>
    <table id="btx-debtor">
      <tr>
        <td>
          <div class="btxheader">
            {ts domain='org.project60.banking'}DEBTOR INFO{/ts}
          </div>
        </td>
      </tr>
      <tr >
        <td>
          <div class="btxlabel">{ts domain='org.project60.banking'}Account{/ts}</div>
          <div class="btxvalue btxl">
            {if $party_ba_references.0}
              {assign var=ba_contact_id value=$party_ba_references.0.contact_id}
              <a title="{$party_ba_references.0.reference_type_label}">{$party_ba_references.0.reference}</a>
              <a href="{crmURL p="civicrm/contact/view" q="reset=1&cid=$ba_contact_id"}">[{$ba_contact_id}]</a>
            {elseif $party_account_ref}
              <span title="{$party_account_reftypename}" class="notfound">{$party_account_ref} ({$party_account_reftype2})</span>
            {else}
              &nbsp;
            {/if}

          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Address{/ts}</div>
          <div class="btxvalue btxl">
            {$payment_data_parsed.street_address}&nbsp;
          </div>
          <div class="btxlabel">&nbsp;</div>
          <div class="btxvalue btxl">
            {$payment_data_parsed.postal_code} {$payment_data_parsed.city}&nbsp;
          </div>
          <div class="btxlabel">{ts domain='org.project60.banking'}Owner{/ts}</div>
          <div class="btxvalue btxl">
            {$payment_data_parsed.name}{if $payment_data_parsed.email}&nbsp;({$payment_data_parsed.email}){/if}
          </div>
          {if $contact}
            <div class="btxlabel">{ts domain='org.project60.banking'}Contact{/ts}</div>
            <div class="btxvalue btxl">
              <a href="{$base_url}/civicrm/contact/view?reset=1&cid={$contact.id}">{$contact.display_name}&nbsp;[{$contact.id}]</a>
            </div>
          {/if}
        </td>
      </tr>
    </table>
    <table id="btx-purpose">
      <tr >
        <td>
          <div class="btxlabel">{ts domain='org.project60.banking'}Purpose{/ts}</div>
          <div class="btxvalue btxl">
            {*{$payment_data_raw.move_msg}&nbsp;*}
            {$payment_data_parsed.purpose}
          </div>
        </td>
      </tr>
    </table>
    <table id="btx-details">
      <tr >
        <td>
          <div class="btxheader collapsible" onclick="cj('#extra').toggle();
              cj(this).toggleClass('collapsible-closed');">
            {ts domain='org.project60.banking'}DETAILS{/ts} <span style="font-weight: normal;">{ts domain='org.project60.banking'}(click to see){/ts}</span>
          </div>
        </td>
      </tr>
      <tr style="display: none;" id="extra">
        <td>
          <table class="explorer">
            {foreach from=$extra_data key=k item=v}
              <tr><td class="xk">{ts domain='org.project60.banking'}{$k}{/ts}</td><td class="btx-detail-entry">{$v}</td></tr>
            {/foreach}
          </table>
        </td>
      </tr>
    </table>
  <div class="clear"></div>
  </div>
  <br/>

  <div align="right" class="clearfix" style="width: 100%;">
    <a href="{$url_skip_back}" class="button {if not $url_skip_back}disabled{/if}  ui-icon-seek-prev"><span title="{ts domain='org.project60.banking'}Back{/ts}"><div class="icon previous-icon ui-icon-seek-prev disabled"></div>{ts domain='org.project60.banking'}Back{/ts}</span></a>

    {if $btxstatus.label != 'Processed' AND $btxstatus.label != 'Ignored'}
      <a id="analyseButton" onClick="analysePayment()" class="button"><span title="{ts domain='org.project60.banking'}Analyse (again){/ts}"><div class="icon preview-icon ui-icon-refresh"></div>{ts domain='org.project60.banking'}Analyse (again){/ts}</span></a>
      {if isset($url_skip_forward)}
        <a href="#" onClick="execute_selected()" class="button"><span title="{ts domain='org.project60.banking'}Confirm and Continue{/ts}"><div class="icon next-icon ui-icon-check"></div>{ts domain='org.project60.banking'}Confirm and Continue{/ts}</span></a>
        <a href="{$url_skip_forward}" class="button"><span title="{ts domain='org.project60.banking'}Skip{/ts}"><div class="icon next-icon ui-icon-seek-next"></div>{ts domain='org.project60.banking'}Skip{/ts}</span></a>
        {if $url_skip_processed}
        <a href="{$url_skip_processed}" class="button"><span title="{ts domain='org.project60.banking'}Skip Processed{/ts}"><div class="icon next-icon ui-icon-seek-next"></div>{ts domain='org.project60.banking'}Skip Processed{/ts}</span></a>
        {/if}
      {else}
        <a href="#" onClick="execute_selected()" class="button"><span title="{ts domain='org.project60.banking'}Confirm and Exit{/ts}"><div class="icon next-icon ui-icon-check"></div>{ts domain='org.project60.banking'}Confirm and Exit{/ts}</span></a>
        <a href="{$url_back}" class="button"><span title="{ts domain='org.project60.banking'}Skip and Exit{/ts}"><div class="icon next-icon ui-icon-seek-next"></div>{ts domain='org.project60.banking'}Skip and Exit{/ts}</span></a>
      {/if}
    {else}
      <a id="analyseButton" onClick="analysePayment()" class="button disabled"><span title="{ts domain='org.project60.banking'}Analyse (again){/ts}"><div class="icon preview-icon ui-icon-refresh"></div>{ts domain='org.project60.banking'}Analyse (again){/ts}</span></a>
      {if isset($url_skip_forward)}
        <a href="" class="button disabled"><span title="{ts domain='org.project60.banking'}Confirm and Continue{/ts}"><div class="icon next-icon ui-icon-check"></div>{ts domain='org.project60.banking'}Confirm and Continue{/ts}</span></a>
        <a href="{$url_skip_forward}" class="button"><span title="{ts domain='org.project60.banking'}Skip{/ts}"><div class="icon next-icon ui-icon-seek-next"></div>{ts domain='org.project60.banking'}Skip{/ts}</span></a>
        {if $url_skip_processed}
        <a href="{$url_skip_processed}" class="button"><span title="{ts domain='org.project60.banking'}Skip Processed{/ts}"><div class="icon next-icon ui-icon-seek-next"></div>{ts domain='org.project60.banking'}Skip Processed{/ts}</span></a>
        {/if}
      {else}
        <a href="" class="button disabled"><span title="{ts domain='org.project60.banking'}Confirm and Exit{/ts}"><div class="icon next-icon ui-icon-check"></div>{ts domain='org.project60.banking'}Confirm and Exit{/ts}</span></a>
        <a href="{$url_back}" class="button"><span title="{ts domain='org.project60.banking'}Skip and Exit{/ts}"><div class="icon next-icon ui-icon-seek-next"></div>{ts domain='org.project60.banking'}Skip and Exit{/ts}</span></a>
      {/if}
    {/if}
    <a href="{$url_back}" class="button" style="float:right;">
      <span title="{ts domain='org.project60.banking'}Back{/ts}"><div class="icon back-icon ui-icon-arrowreturnthick-1-w"></div>{ts domain='org.project60.banking'}Back to transaction list{/ts}</span>
    </a>
  </div>

  {if $btxstatus.label != 'Processed' AND $btxstatus.label != 'Ignored'}
    <br/>
    <div id="generating_suggestions" align="center" hidden="1">
      <br/><br/>
      <img name="busy" src="{$config->resourceBase}i/loading.gif"/>
      <font size="+1">{ts domain='org.project60.banking'}Generating suggestions...{/ts}</font>
      <br/><br/>
    </div>
    <table class="suggestions">
      <tr>
        <td  class="layout">
          <table>
            {foreach from=$suggestions item=suggestion name=action_loop}
              <tr  class="suggestion {if $smarty.foreach.action_loop.first}suggestion-selected{/if}">
                <td class="prob" width="60" align="center">
                  <span style="color: {$suggestion.color};">{$suggestion.probability}</span>
                  <input type="radio" name="selected_suggestion" value="{$suggestion.hash}" style="display: none;" {if $smarty.foreach.action_loop.first}checked{/if} />
                </td>
                <td width="10" align="center" style="background-color: {$suggestion.color};"></span>
                </td>
                <td class="suggest">
                  <form id="{$suggestion.hash}" action="{$url_execute}" method="POST">
                  <input type="hidden" name="execute_suggestion" value="{$suggestion.hash}"/>
                  {* These will be generated by the matcher plugins *}
                  <h4 style="color: {$suggestion.color};">{$suggestion.title}</h4>
                  {$suggestion.visualization}
                  {$suggestion.actions}
                  </form>
                </td>
              <tr>
              {/foreach}
          </table>
        </td>
      </tr>
    </table>

  {else}
    <br/><br/>
    <h2>{$status_message}</h2>
    <br/>
    {$execution_info.visualization}
  {/if}


<!-- Required JavaScript functions -->
{literal}
<script language="JavaScript">
function execute_selected() {
  var selected_suggestion = cj('input[name=selected_suggestion]:checked').val();
  document.getElementById(selected_suggestion).submit();
}

// add listener to all suggestions, so that changes automatically select the given item
cj(".suggestion").on('change', '*', select_suggestion);
cj(".suggestion").on('click', '*', select_suggestion);

function select_suggestion(e) {
  cj(".suggestion").removeClass('suggestion-selected');
  var suggestion = cj(e.target).closest(".suggestion");
  suggestion.addClass('suggestion-selected');
  var button = suggestion.find("input[name=selected_suggestion]");
  button.prop('checked', true);
}


function analysePayment() {
  var reload_regex = new RegExp("(execute=)[0-9]+", 'ig');

  if (cj("#analyseButton").hasClass('disabled')) return;

  // disable ALL buttons
  cj(".button").addClass('disabled');
  cj(".button").attr("onclick","");

  // remove old suggestions
  cj(".suggestions").remove();
  cj("#generating_suggestions").show();

  // show busy indicator

  // AJAX call the analyser
  var query = {'q': 'civicrm/ajax/rest', 'sequential': 1};
  // set the list or s_list parameter depending on the page mode
  query['list'] = "{/literal}{$payment->id}{literal}";
  CRM.api('BankingTransaction', 'analyselist', query,
    {success: function(data) {
        if (!data['is_error']) {
          // remove 'execute' bit from URL before reload
          var newURL = window.location.href.replace(reload_regex, '');
          if (window.location.href == newURL) {
            window.location.reload(false);
          } else {
            window.location = newURL;
          }
        } else {
          cj('<div title="{/literal}{ts domain='org.project60.banking'}Error{/ts}{literal}"><span class="ui-icon ui-icon-alert" style="float:left;"></span>' + data['error_message'] + '</div>').dialog({
            modal: true,
            buttons: {
              Ok: function() {
                window.location = window.location.href.replace(reload_regex, '');
              }
            }
          });
        }
      }
    }
  );
}

/**
 * common function to bring CiviCRM 4.5+ popups into the game
 */
function banking_open_link(dirty_link, replacements, asPopup) {
  // "clean" the link
  var link = cj("<div/>").html(dirty_link).text();

  // replace the tokens
  for (var token in replacements) {
    link = link.replace(token, replacements[token]);
  }

  if (asPopup && {/literal}{$popups_allowed}{literal}) {
    // popup requested and possible => do it!
    var popup_node = cj('<a href="' + link + '" class="crm-popup" />');
    popup_node.click(CRM.popup); // add handler
    popup_node.click(); // execute handler
  } else {
    // open in an extra tab
    window.open(link, "_blank");
  }
}
</script>
{/literal}
