
{* This page is generated by CRM/Banking/Page/Review.php *}

<div align="right">
	<a href="{$config->civiRelativeURL}civicrm/banking/review?id={$payment.id}&amp;run" class="button"><span title="Process (again)"><div class="icon"></div>Process (again)</span></a>
	{if isset($next_pid)}
	<a href="{$config->civiRelativeURL}civicrm/banking/review?id={$next_pid}" class="button"><span title="Confirm and Continue"><div class="icon next-icon"></div>Confirm and Continue</span></a>
	<a href="{$config->civiRelativeURL}civicrm/banking/review?id={$next_pid}" class="button"><span title="Skip"><div class="icon next-icon"></div>Skip</span></a>
	{else}
	<a href="{$config->civiRelativeURL}civicrm/banking/payments" class="button"><span title="Confirm and Exit"><div class="icon next-icon"></div>Confirm and Exit</span></a>
	<a href="{$config->civiRelativeURL}civicrm/banking/payments" class="button"><span title="Skip and Exit"><div class="icon next-icon"></div>Skip end Exit</span></a>
	{/if}
</div>
<br/><br/>

<table border="1">
	<tr>
		<div title="Edit info" class="crm-clear crm-inline-block-content">
    		<div class="crm-summary-row">
				<div class="crm-label">Date</div>
				<div class="crm-content">{$payment.booking_date} {$payment.currency}&nbsp;&nbsp;&nbsp;&nbsp;[valuta {$payment.value_date}]</div>
			</div>
	      	<div class="crm-summary-row">
	        	<div class="crm-label">Amount</div>
	        	<div class="crm-content crm-contact-job_title">{$payment.amount} {$payment.currency}</div>
			</div>
	      	<div class="crm-summary-row">
	        	<div class="crm-label">To Account</div>
	        	<div class="crm-content crm-contact-job_title">Unknown</div>
			</div>
	      	<div class="crm-summary-row">
	        	<div class="crm-label">From</div>
	        	<div class="crm-content crm-contact-job_title">{$payment_data_parsed.name}</div>
			</div>
		</div>
	
		<table>
			<tr>
				<th colspan="3">Suggestions</th>
			</tr>
			{foreach from=$suggestions item=suggestion name="action_loop"}
			<tr bgcolor="#FF0000" valign="middle">
				<td valign="middle" bgcolor="{$action.color}" width="10" align="rigth">
					<input valign="middle" type="checkbox" name="action" {if $smarty.foreach.action_loop.first}checked{/if}/></td>
				<td bgcolor="{$suggestion.color}" width="100" align="center">{$action.probability}</td>
				<td bgcolor="{$suggestion.color}">
					{* These will be generated by the matcher plugins *}
					<h2>{$suggestions.title}</h2>
					<p>{$suggestions.content}</p>
				</td>
			<tr>
			{/foreach}
		</table>

		<!--table>
			<tr>
				<th colspan="3">Proposed Actions</th>
			</tr>
			{foreach from=$actions item=action name="action_loop"}
			<tr bgcolor="#FF0000" valign="middle">
				<td valign="middle" bgcolor="{$action.color}" width="10" align="rigth">
					<input valign="middle" type="checkbox" name="action" {if $smarty.foreach.action_loop.first}checked{/if}/></td>
				<td bgcolor="{$action.color}" width="100" align="center">{$action.probability}</td>
				<td bgcolor="{$action.color}">

				{* These will be generated by the matcher plugins *}
				{if $action.type == 'manual'}
				<h2>Manual Booking</h2>
				<p>Payment has been manually processed, and will be matched to the following financial transaction: <span class="icon crm-icon Contribution-icon"></span><input type="text" class="form-text required ac_input" id="source_contact_id" value="<enter or drop transaction id>" name="source_contact_id" autocomplete="off"></p>

				{elseif $action.type == 'not civicrm'}
				<h2>Not related to CiviCRM</h2>
				<p>This payment is not related to CiviCRM. It will only be marked "unrelated".

				{elseif $action.type == 'donation'}
				<h2>Donation</h2>
				<p>This payment is an expected donation of <input type="text" class="form-text required ac_input" id="source_contact_id" value="{$payment.account_owner}" name="source_contact_id" autocomplete="off"></a>

				{elseif $action.type == 'new donation'}
				<h2>Unexpected Donation</h2>
				<p>This payment is donation from a new contact. Actions:<ol><li>The contact <input type="text" class="form-text required ac_input" id="source_contact_id" value="{$payment.account_owner}" name="source_contact_id" autocomplete="off"> will be created</li><li>a contribtuion of type <input type="text" class="form-text required ac_input" id="source_contact_id" value="donation" name="source_contact_id" autocomplete="off"> will be generated.</li></ol></a>

				{elseif $action.type == 'membership fee'}
				<h2>Membership payment</h2>
				<p>This payment is a membership payment for the year
					<select class="form-select required" id="banking-importer-plugin" name="importer-plugin" onchange="todo(this.value);">
              			<option selected="selected" value="2012">2012</option>
              			<option value="2011">2011</option>
              			<option value="2013">2013</option>
            		</select>
            	of contact <input type="text" class="form-text required ac_input" id="source_contact_id" value="{$payment.account_owner}" name="source_contact_id" autocomplete="off">.

				{else}
				<h2>{$action.type}</h2>
				{/if}
				</td>

			<tr>
			{/foreach}
		</table-->
	</tr>
<table>
